### ISSUE TITLE
Please provide example of closing the app using menu and (destroy-all-windows-and-quit) function.

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#10]
I have this little example which closely resembles your example: 
https://github.com/bigos/Pyrulis/blob/d6e4e55a76e2e000d680250c89f5f73864871730/Lisp/cl-gtk4-example.lisp#L127 

But I need help finding how to call your gio:*application* in the example context.

**Comment by bohonghuang** [comment]
I wrote an example of the GTK menu with the newly added macro `define-application` used for interactive programming, but I can't guarantee its stability in terms of API yet. Just for your reference:

https://github.com/bohonghuang/cl-gtk4/blob/ad8fae4171bdf9532cd268d3e0a57548b3d92ec6/examples/gtk4.lisp#L95-L152

**Comment by bigos** [comment]
Thank you, that should be enough to point me in the right direction.

**Comment by bigos** [comment]
https://github.com/bohonghuang/cl-gtk4/blob/ad8fae4171bdf9532cd268d3e0a57548b3d92ec6/examples/gtk4.lisp#L131
is the **temporary** answer
