### ISSUE TITLE
Please comment on pros and cons of placing define-application over a smaller portion of code.

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#11]
In this example:
https://github.com/bigos/Pyrulis/blob/da5decdb6a8639511a5422a7b365106b2332ce6e/Lisp/menu-cairo-test.lisp#L161 

I have modified your cl-gtk4 examples to have menu and cairo tests in one file. I have noticed that I can move some code outside `define-application`, and the code still seems to work. Can you please comment if it is OK to do it that way?

**Comment by bohonghuang** [comment]
> Can you please comment if it is OK to do it that way?

Sure. The `define-application` is currently used for interactive programming, by which you can recompile a chunk of code and reload the window with `C-c C-c` in Emacs while your application runs. Therefore, you can put almost any code you want to lively recompile and reload with the window defined in `define-main-window` into `define-application`. You can move your code outside `define-application` or remove this macro once you no longer need it.

**Comment by bigos** [comment]
How do I remove `define-application`? The naive attempt did not work. Using `macroexpand-all` in Emacs I can see what code is generated. So I may figure it out.

Perhaps this question should wait for a more concrete example. For now, you have answered my initial question. Thank you very much.

**Comment by bohonghuang** [comment]
> How do I remove `define-application`?

Perhaps you can refer to commit 7cba4f17f250ae38755ef4bd592e4a78645999a8, where I rewrote all the example code using `define-application` and `define-main-window` equivalently.

**Comment by bohonghuang** [comment]
Having other questions, feel free to open a new issue.
