### ISSUE TITLE
How do I use Gdk Rectangle?

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#18]
https://docs.gtk.org/gdk4/struct.Rectangle.html

I am trying to add popover and need it to show at mouse coordinates.

**Comment by bohonghuang** [comment]
It could be implemented with CFFI. I added the CFFI definition for `Rectangle` and an example for it:

https://github.com/bohonghuang/cl-gtk4/blob/1c7607f4084214bf9bfe54d574ed7677669cb935/examples/gdk4.lisp#L24-L54
