### ISSUE TITLE
Setting text doesn't work with unicode strings

### ISSUE THREAD

**Issue by rationalis-petra** [bohonghuang/cl-gtk4#22]
I've noticed several functions that set/provide/insert text - for example `(setf text-buffer-text)` will, in the GTK version accept a length (bytes) parameter, but the wrappers will populate this parameter with `length` called on the argument. (i.e. number of characters, *not* number of bytes). In the case where the text contains any unicode characters, this can cause bugs, as the length provided by CL is wrong.

**Comment by bohonghuang** [comment]
Thank you for your feedback. The strings passed through CFFI are terminated with `\0`, so I changed the length in the parameters to `-1`. Now, `(setf (gtk:text-buffer-text ...) ...)` and `(setf (gtk:entry-buffer-text ...) ...)` should be able to use UTF-8 strings.
