### ISSUE TITLE
Please provide example of using XML in building UI

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#26]
Mostly I need an example of translating:

https://docs.gtk.org/gtk4/getting_started.html

https://docs.gtk.org/gtk4/getting_started.html#packing-buttons-with-gtkbuilder
```
  /* Construct a GtkBuilder instance and load our UI description */
  GtkBuilder *builder = gtk_builder_new ();
  gtk_builder_add_from_file (builder, "builder.ui", NULL);

  /* Connect signal handlers to the constructed widgets. */
  GObject *window = gtk_builder_get_object (builder, "window");
  gtk_window_set_application (GTK_WINDOW (window), app);
```

I do not understand how to translate variable pairs like *builder and builder, one with asterix and another without one.

**Comment by bohonghuang** [comment]
You usually don't need to worry about pointer issues in Lisp because `gobject-introspection` automatically handles object ownership and memory. Your code can be simply translated as:

``` lisp
(let ((builder (gtk:make-builder)))
  (gtk:builder-add-from-file builder "/path/to/ui/file")
  (let ((window (gtk:builder-get-object builder "window")))
    (setf (gtk:window-application window) gtk:*application*)))
```

**Comment by bigos** [comment]
Thank you for the explanation. I will try it and let you know if I have any problems.

**Comment by bigos** [comment]
2 differennt versions of SBCL give me the error:

> Unhandled memory fault at #x0.
>    [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

 `     (builder (gtk4:make-builder :filename "/home/jacek/Programming/Lisp/lispy-experiments/exmal/builder.ui"))
 `

**Comment by bohonghuang** [comment]
> 2 differennt versions of SBCL give me the error:
> 
> > Unhandled memory fault at #x0.
> >    [Condition of type SB-SYS:MEMORY-FAULT-ERROR]
> 
>  `     (builder (gtk4:make-builder :filename "/home/jacek/Programming/Lisp/lispy-experiments/exmal/builder.ui"))
>  `

It seems like a NPE. Did you run the code after the initialization of GTK4?

**Comment by bigos** [comment]
This variant also gives the error
```

(let ((builder (gtk4:make-builder)))
  (builder-add-from-file builder
                         "/home/jacek/Programming/Lisp/lispy-experiments/exmal/builder.ui")
  )

```

**Comment by bohonghuang** [comment]
> This variant also gives the error
> ```
> 
> (let ((builder (gtk4:make-builder)))
>   (builder-add-from-file builder
>                          "/home/jacek/Programming/Lisp/lispy-experiments/exmal/builder.ui")
>   )
> 
> ```

Understood, I will delve deeper into this issue later.

**Comment by bohonghuang** [comment]
I still cannot reproduce your issue. However, I suspect that you are not loading the `.ui` file while running the GTK application. I have written an example for your reference:

https://github.com/bohonghuang/cl-gtk4/blob/e39156387d9b07e4a813c804c79b980d99002a3b/examples/gtk4.lisp#L235-L249

**Comment by bigos** [comment]
Thank you for the example
