### ISSUE TITLE
Working with GTK Picture objects

### ISSUE THREAD

**Issue by jonathanabennett** [bohonghuang/cl-gtk4#33]
I need to add images to my game. In cl-cffi-gtk, they did this via PixBufs but it seems like the [Picture Class](https://docs.gtk.org/gtk4/class.Picture.html) is the way I need to go. But I cannot get it to load. Here is my current code
``` lisp
  (let ((frame (gtk:make-frame :label (cu/full-name u)))
        (statblock (gtk:make-box :orientation gtk:+orientation-vertical+ :spacing 5))
        (img (gtk:make-picture :filename (namestring (cu/display u)))))
    (setf (gtk:frame-child frame) statblock)
    (gtk:box-append statblock img)
    frame)
```
`frame` is rendered in another function. This same code works when I replace `gtk:make-picture` with `gtk:make-image`, but it seems like make-image is for displaying images at a fixed size, not at natural size (which is what I want).

EDIT: Extraneous code rendering labels and other rows of this stat block have been removed. But the code fails whether they are commented out or not. And I am sure that `(cu/display u)` contains the path to the correct file because `gtk:make-image` puts a very tiny rendering of that image inside the frame whereas `gtk:make-picture` does not.

**Comment by bohonghuang** [comment]
I suspect that your pathname contains a `~` that cannot be expanded by GTK. To address this, you need to use `(namestring (truename (cu/display u)))` to expand it on the Lisp side.

**Comment by jonathanabennett** [comment]
That didn't help either, and when I `(format t "~a" (cu/display u))`, I get the full path `/Users/jonathanbennett/.roswell/lisp/quicklisp/local-projects/megastrike/data/images/units/vehicles/Pumapat.png`

**Comment by bohonghuang** [comment]
Can you load `cl-gdk4` and try this in your application?

```lisp
(let ((texture (gdk:make-texture :path "/path/to/your/image/file")))
  (format t "WIDTH: ~A HEIGHT: ~A~%" (gdk:texture-width texture) (gdk:texture-height texture)))
```

**Comment by jonathanabennett** [comment]
the above snippet accurately reports the size of the image (84x72 px), but the image is still not rendering. It is a png file, is the a possible reason for the error?

**Comment by bohonghuang** [comment]
Have you tried a minimal example like this?

```lisp
(define-application (:name picture-test
                     :id "org.bohonghuang.gtk4.issue-33")
  (define-main-window (window (make-application-window :application *application*))
    (setf (window-title window) "Picture Test"
          (window-child window) (make-picture :filename "/path/to/your/image/file"))
    (unless (widget-visible-p window)
      (window-present window))))
```

The snippet is tested to run on both Windows and GNU/Linux.

**Comment by jonathanabennett** [comment]
The minimum example you just posted works on MacOS as well (just tested it now). Is it possible that you can't have a picture inside a box or inside a ListBoxChild?

**Comment by bohonghuang** [comment]
The minimum size of `Picture` defaults to zeros, so you could use `(setf (widget-size-request picture) '(100 100))` to set the size manually after creating a picture.

**Comment by jonathanabennett** [comment]
Ok, I've got that working. I'm struggling to figure out how I could draw the picture in a drawing area.

**Comment by bohonghuang** [comment]
> Having `(cairo:stroke)` as the final line also does not draw anything on the screen. In both cases, I get a blank white screen which is 500 by 500 pixels. I expected the image to be displayed 100 pixel down from the top and over from the left.

You haven't set a drawing area using functions like `cairo:rectangle`, so there won't be anything drawn. The following code can help you draw your image in the center of the canvas.

```lisp
(defun draw-func (area cr canvas-width canvas-height)
    (declare (ignore area)
             (optimize (speed 3)
                       (debug 0)
                       (safety 0)))
  (let ((texture (gdk:make-texture :path (namestring (truename (merge-pathnames "images/units/mechs/Akuma.png" *data-folder*))))))
    (let* ((canvas-width (coerce (the fixnum canvas-width) 'single-float))
           (canvas-height (coerce (the fixnum canvas-height) 'single-float))
           (width (coerce (the fixnum (gdk:texture-width texture)) 'single-float))
           (height (coerce (the fixnum (gdk:texture-height texture)) 'single-float))
           (x (/ (- canvas-width width) 2.0))
           (y (/ (- canvas-height width) 2.0)))
      (cairo:rectangle x y width height)
      (gdk:cairo-set-source-pixbuf cr (gdk:pixbuf-get-from-texture texture) (coerce x 'double-float) (coerce y 'double-float))
      (cairo:fill-path)
      (with-gdk-rgba (color "#FF0000")
        (cairo:rectangle x y width height)
        (gdk:cairo-set-source-rgba cr color)
        (cairo:set-line-width 3.0)
        (cairo:stroke)))))
```

**Comment by jonathanabennett** [comment]
Ok, got that part working within my program. The problem now is a matter of scaling. Based on reading the GDK Documentation and a few examples in Python, it appears I need to use [GdkPixbuf.Pixbuf.scale_simple](https://docs.gtk.org/gdk-pixbuf/method.Pixbuf.scale_simple.html), but I can't find it in GDK4. If I use `(cairo:scale)`, it scales all the coordinates (obviously), meaning the x and y origin for the image shifts.

**Comment by bohonghuang** [comment]
Okay, previously there were no bindings generated for GdkPixbuf because I thought it had fewer use cases. Now, I have added it in commit 6ab0131af4e3007032053fb8eb807a3456a9fe3d. Please upgrade to use it.

**Comment by jonathanabennett** [comment]
Next question. The images I have are all black and white. I'd like to mark which team they are on by painting the unit the team's color (which I've got in the format returned by `gdk:rgba-to-string`). I looked at [GdkPixbuf.Pixbuf.composite-color-simple](https://docs.gtk.org/gdk-pixbuf/method.Pixbuf.composite_color_simple.html), but it wants a `GUINT32` rather than an RGBA color structure. Should I be controlling this in Cairo?

**Comment by bohonghuang** [comment]
1. You can directly provide the color value in the format `#xRRGGBBAA`. 
2. If you are familiar with `cffi`, the conversion between `GdkRGBA` and the color value should not be difficult:
``` lisp
(cffi:defcstruct gdk-rgba
  (red :float)
  (green :float)
  (blue :float)
  (alpha :float))

(cffi:defcstruct rgba32
  (red :uint8)
  (green :uint8)
  (blue :uint8)
  (alpha :uint8))

(defun rgba-color-value (rgba)
  (cffi:with-foreign-slots (((r1 red) (g1 green) (b1 blue) (a1 alpha)) (gobj:object-pointer rgba) (:struct gdk-rgba))
    (cffi:with-foreign-object (pointer '(:struct gdk-rgba))
      (cffi:with-foreign-slots (((r2 red) (g2 green) (b2 blue) (a2 alpha)) pointer (:struct rgba32))
        (setf r2 (round (* r1 #xFF))
              g2 (round (* g1 #xFF))
              b2 (round (* b1 #xFF))
              a2 (round (* a1 #xFF))))
      (cffi:mem-ref pointer :uint32))))

(with-gdk-rgba (rgba "#FF0000FF")
  (assert (= (rgba-color-value rgba) #xFF0000FF)))
```
