### ISSUE TITLE
Compilation error: GIO missing APPLICATION-QUIT

### ISSUE THREAD

**Issue by jonathanabennett** [bohonghuang/cl-gtk4#34]
In order to load the latest version, I am using a git submodule to put this application in the /libs/cl-gtk4 folder. When attempting to load `(ql:quickload :cl-gtk4)` in a fresh Slime session, I recevie the following error:

```
CL-USER> (ql:quickload :cl-gtk4)
To load "cl-gtk4":
  Load 1 ASDF system:
    cl-gtk4
; Loading "cl-gtk4"
[package gtk4]....................................
..................................................
.................
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "APPLICATION-QUIT" not found in the GIO package.
;   
;       Line: 69, Column: 44, File-Position: 2688
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/jonathanbennett/.roswell/lisp/quicklisp/local-projects/megastrike/libs/cl-gtk4/gtk4.lisp" {70052A1083}>
```

**Comment by bohonghuang** [comment]
This is strange because this symbol should be auto-generated. Try placing the `cl-gtk4` repository in the `local-projects` directory and see if that works.

**Comment by jonathanabennett** [comment]
Ok, moving it to `local-projects` worked, but now I'm not seeing any symbols being exported from cl-gdk. Here is a screenshot of a slime session showing that the auto-complete can only find the `*ns*` symbol in the gdk package. Using `(gdk::` and the autocomplete only finds those symbols directly referenced in the gdk4.lisp file. My project also fails to compile because `rgba-parse` is not a symbol in `gdk`.

![Screenshot 2023-10-12 at 14 06 01](https://github.com/bohonghuang/cl-gtk4/assets/17274248/2d7bfdfd-a3fe-47d1-9e9e-f6a5e74970c0)

**Comment by bohonghuang** [comment]
Can you try `[slime/sly]-eval-buffer` on `gdk4.lisp`?

**Comment by bohonghuang** [comment]
This is the expected macro expansion of `(gir-wrapper:define-gir-namespace "Gdk" "4.0")` in the file:

![image](https://github.com/bohonghuang/cl-gtk4/assets/11132087/7c5e46e2-92eb-4046-b070-5e45cf4d070c)

**Comment by jonathanabennett** [comment]
It appears Ultralisp has not yet found the new version and my computer is getting hung up halfway between the two versions. According to their webpage, they will be crawling this page tonight my time. I will wait until tomorrow morning and contact them if it isn't resolved.

**Comment by jonathanabennett** [comment]
I am now getting a new error message.
``` lisp
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION GIR::NSGET (6)>
when called with arguments
  (NIL GDK4::NEW-FROM-FILENAME).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```
I get this same error message every time the execution gets to a function in GDK. So far, I have gotten it for `gdk:rgba-parse` and `gdk:new-from-filename`.

**Comment by bohonghuang** [comment]
I got it. `gdk-pixbuf2` is not installed in your system. Furthermore, there are some issues with the newly added definition in `gdk4.lisp`. I will address them in a later commit. Please get  `gdk-pixbuf2` installed and update your local repo accordingly after that.

**Comment by bohonghuang** [comment]
This issue should be fixed in commit 407f780056d6fbbbcf17562ecd638a18a90a9a12. Please forgive me for performing a rebase due to my OCD. If necessary, please reset --hard the local repository to the latest remote branch.

**Comment by jonathanabennett** [comment]
Commit `407f780` resolves the issues.

**Comment by dacodas** [comment]
I also experienced this. I believe that I was missing some glib development files on my system. After installing them, I needed to reinstall the Quicklisp packages entirely, and it then worked
