### ISSUE TITLE
无法编译程序

### ISSUE THREAD

**Issue by PAGA-Official** [bohonghuang/cl-gtk4#35]
你好，我在运行此条命令：(asdf:operate :program-op :cl-gtk4/example)时出现了如下问题：

Symbol "SIMPLE" not found in the GTK4.EXAMPLE package.

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "gtk4.exa...">
   [Condition of type SB-INT:SIMPLE-READER-PACKAGE-ERROR]
请问该如何解决，谢谢

**Comment by bohonghuang** [comment]
已在提交 41edd7a986c8a0a40ab0409cdd99130c0e9969ec 中修复，感谢反馈。
