### ISSUE TITLE
无法编译程序

### ISSUE THREAD

**Issue by PAGA-Official** [bohonghuang/cl-gtk4#36]
老兄还是不行啊，报错信息：
failed AVER: (SB-THREAD::THREAD-P SB-IMPL::THREAD)
This is probably a bug in SBCL itself. (Alternatively, SBCL
might have been corrupted by bad user code, e.g. by an undefined
Lisp operation like (FMAKUNBOUND 'COMPILE), or by stray pointers
from alien code or from unsafe Lisp code; or there might be a
bug in the OS or hardware that SBCL is running on.) If it seems
to be a bug in SBCL itself, the maintainers would like to know
about it. Bug reports are welcome on the SBCL mailing lists,
which you can find at <http://sbcl.sourceforge.net/>.
   [Condition of type SB-INT:BUG]

**Comment by bohonghuang** [comment]
请问你的 SBCL 版本是多少？你是在 32 位的 ARM 上运行的吗？

**Comment by PAGA-Official** [comment]
SBCL版本为2.3.2，操作系统为Windows 10 x64

**Comment by bohonghuang** [comment]
> SBCL版本为2.3.2，操作系统为Windows 10 x64

是 Msys2 的环境吗？直接执行 `sb-ext:save-lisp-and-die` 有出现类似的错误吗？

**Comment by PAGA-Official** [comment]
不是，是Windows命令行版本，运行所给命令会报错，截图如下：
![image](https://github.com/bohonghuang/cl-gtk4/assets/123882032/e31d478d-0e1b-43f8-9389-e754f7a193c1)

**Comment by bohonghuang** [comment]
请运行 `(sb-ext:save-lisp-and-die "test-sbcl.exe" :executable t)`

**Comment by PAGA-Official** [comment]
没有问题，成功退出

**Comment by bohonghuang** [comment]
那么运行 `(progn (ql:quickload :cl-gtk4/example) (sb-ext:save-lisp-and-die "test-sbcl.exe" :executable t))` 呢？

**Comment by PAGA-Official** [comment]
在Emacs里使用slime运行命令统统报错，但是在命令行下的sbcl顺利通过，太诡异了

**Comment by bohonghuang** [comment]
> 在Emacs里使用slime运行命令统统报错，但是在命令行下的sbcl顺利通过，太诡异了

使用 SBCL 生成可执行文件时不能有其他线程正在执行，SLIME/Sly 都会创建新的的线程用于交互

**Comment by PAGA-Official** [comment]
问题解决了！Thanks，dude！

**Comment by bohonghuang** [comment]
客气了。
