### ISSUE TITLE
No symbol named "POINTER-OBJECT"

### ISSUE THREAD

**Issue by kinderferraz** [bohonghuang/cl-gtk4#55]
Hi!
I've been having some trouble loading the project `:cl-gtk4`, with the following symbol missing from the wrapper package. 

![image](https://github.com/bohonghuang/cl-gtk4/assets/33708256/5412dd3c-b48e-42bb-b59d-c4c6ee8cb397)

There is no problem from the gdk4 package and the dependecy libraries. I also tried loading all the examples and this causes troubles with the simple-menu, when trying to exit from the drop-down on the title-bar.

I already cloned all the dependecies into `~/quicklisp/local-projects` to ensure the latest version, but unfortunately i cannot update libgtk-4 and libgio, currently in this version;
![image](https://github.com/bohonghuang/cl-gtk4/assets/33708256/e22cebfd-10c4-499f-a371-e9bb6d53e7d3)

Is there something I am missing? Can you help me load the project correctly please?

**Comment by bohonghuang** [comment]
Please use the Git version of the `cl-gobject-introspection-wrapper` library. The older version of this library is already present in the Quicklisp distribution. However, make sure to load the Git clone version located in the `local-projects` directory. For example, you can observe the source code location to which the symbol `gir-wrapper:define-gir-namespace` jumps to determine the version being loaded. But generally, the version located in the `local-projects` path will be loaded with higher priority.

**Comment by kinderferraz** [comment]
Thanks!! I had the git version sym linked to `local-projects`, but checking the path of the loaded file, turns out there was an older version cached. Deleting the cache solved the issue. Many thanks again.
