### ISSUE TITLE
Connect widget to key-pressed event

### ISSUE THREAD

**Issue by garlic0x1** [bohonghuang/cl-gtk4#60]
I am trying to implement tab completion in an entry field, I have this code which I based on [this thread](https://stackoverflow.com/questions/74590904/gtk-4-key-press-event-handler) but nothing is happening.

```lisp
    (let ((controller (make-event-controller-key)))
      (connect controller "key-pressed"
               (lambda (&rest rest)
                 (print rest)))
      (widget-add-controller entry controller))
```

I also tried connecting the event directly to the `entry` widget like this but it also did nothing

```lisp
(connect entry "key-press-event" (lambda (&rest rest) (print rest)))
```

**Comment by bohonghuang** [comment]
Since you did not provide the complete code, I cannot reproduce your issue. But the following example works for me:

```lisp
(define-application (:name key-event-test
                     :id "org.bohonghuang.gtk4-example.key-event-test")
  (define-main-window (window (make-application-window :application *application*))
    (setf (window-title window) "Key Event Test")
    (let ((controller (make-event-controller-key)))
      (connect controller "key-pressed" (lambda (&rest args)
                                          (print args)
                                          (values gdk:+event-propagate+)))
    (widget-add-controller window controller))
    (unless (widget-visible-p window)
      (window-present window))))
```

**Comment by garlic0x1** [comment]
Okay, I guess the controller needs to be added to a window instead of a regular widget.  
I was trying to add it to an entry widget made with `(make-entry)` as seen [here](https://github.com/garlic0x1/learn-gtk/blob/master/src/prompt.lisp#L60)

Is there a way to do this?  Also while attaching it to the window works, it only works anywhere outside of the entry widget so I suspect I am conflicting with the default event handlers for it... idk
