### ISSUE TITLE
Making executable

### ISSUE THREAD

**Issue by apr3vau** [bohonghuang/cl-gtk4#64]
Hello, I'm trying to make executables, under SBCL, and have some additional strange findings...

Just as your description, `asdf:program-op` works, but it seems that `program-op` does not have a core compression option; and if I try to use `sb-ext:save-lisp-and-die` straightly, another issue happened: The restored image cannot load GIR namespace correctly, even if I have specified correct path to `girepository-1.0/` using `gir:repository-prepend-search-path`. The required namespace seems always empty, expressions like `(gir:nget (gir:require-namespace "Gtk") "Application")` will return `NIL`.

If I just want to apply core compression, `uiop:dump-image` will be useful, which is the inner function of `program-op`. The core facility that makes it useful maybe is `uiop:restore-image`, which will automatically execute after image loaded, and will reset variables to previous state. This will eliminate the namespace problem, but I don't know which part it restored is critical. And there is another question: Can I ship this executable to other machines that do not have the same GTK environment? It's obvious that those restored configurations can only work under the environment that same with mine. I haven't tested in another machine, but I suspect that it will happend... Something like requiring users to install dependencies in linux can't be a solution, as those foreign object may not have identical pathnames, like under NixOS, and things will also be broken...

At least I expect the `gir:repository-prepend-search-path` will be functional in runtime, but it's not. It can be reproduced in a saved SBCL image using `(ql:quickload :cl-gtk4/example)` then `(sb-ext:save-lisp-and-die "test" :toplevel 'gtk4.example:simple-menu :executable t)`. Core compression will not affect the problem. Maybe we can do something like rewind the initialize process of `cl-gobject-introspection` ?...

I'm really glad to know any additional informations, and I will also try my best to help. Thank you! :D

**Comment by bohonghuang** [comment]
> Just as your description, `asdf:program-op` works, but it seems that `program-op` does not have a core compression option; 

Add the following code to the ASD file of your application:

```lisp
#+sb-core-compression
(defmethod asdf:perform ((o asdf:image-op) (c asdf:system))
  (uiop:dump-image (asdf:output-file o c) :executable t :compression t))
```

> and if I try to use `sb-ext:save-lisp-and-die` straightly, another issue happened: The restored image cannot load GIR namespace correctly, even if I have specified correct path to `girepository-1.0/` using `gir:repository-prepend-search-path`. The required namespace seems always empty, expressions like `(gir:nget (gir:require-namespace "Gtk") "Application")` will return `NIL`.

If the following code is functioning properly, the problem should not occur:

https://github.com/bohonghuang/cl-gtk4/blob/ff60e3495cdbba5c09d0bb8aa49f3184cc060c8e/cl-gtk4.asd#L16-L22

> If I just want to apply core compression, `uiop:dump-image` will be useful, which is the inner function of `program-op`. The core facility that makes it useful maybe is `uiop:restore-image`, which will automatically execute after image loaded, and will reset variables to previous state.

**Comment by apr3vau** [comment]
Thank you! I will take a look...
