### ISSUE TITLE
Compilation error when expanding RUN-IN-MAIN-EVENT-LOOP macro

### ISSUE THREAD

**Issue by hlin91** [bohonghuang/cl-gtk4#66]
Hello. I am running into compilation errors when using the RUN-IN-MAIN-EVENT-LOOP macro for making thread-safe calls. For example, when I have the line
```
(gtk4:run-in-main-event-loop (widget-remove-css-class·skip-button "suggested-action"))       
```
in my Lisp file, it throws this error.
```
main.lisp:70:24:
   error: 
     during macroexpansion of
     (RUN-IN-MAIN-EVENT-LOOP (WIDGET-REMOVE-CSS-CLASS SKIP-BUTTON
                                                      "suggested-action")).
     Use *BREAK-ON-SIGNALS* to intercept.
     
      Error while parsing arguments to RUN-IN-MAIN-EVENT-LOOP DEFMACRO:
        odd number of elements in keyword/value list: (WIDGET-REMOVE-CSS-CLASS
                                                       SKIP-BUTTON
                                                       "suggested-action")
```
When I call a function that contains a ":" in the name, it gives me a different error, stating that it expected the :priority flag.
```
(gtk4:run-in-main-event-loop (adw:carousel-scroll-to image-carousel image t))
```
```
main.lisp:68:24:
   error: 
     during macroexpansion of
     (RUN-IN-MAIN-EVENT-LOOP (ADW:CAROUSEL-SCROLL-TO IMAGE-CAROUSEL IMAGE ...)). Use
     *BREAK-ON-SIGNALS* to intercept.
     
      Error while parsing arguments to RUN-IN-MAIN-EVENT-LOOP DEFMACRO:
        unknown keyword: ADW:CAROUSEL-SCROLL-TO; expected one of :PRIORITY
```
And supplying the :priority flag results in a different compilation error.
```
(gtk4:run-in-main-event-loop :priority glib:+priority-default+ (adw:carousel-scroll-to image-carousel image t))
```
```
main.lisp:68:24:
  error: 
    during macroexpansion of
    (RUN-IN-MAIN-EVENT-LOOP :PRIORITY
      GLIB:+PRIORITY-DEFAULT+
      ...).
    Use *BREAK-ON-SIGNALS* to intercept.
    
     Error while parsing arguments to RUN-IN-MAIN-EVENT-LOOP DEFMACRO:
       :PRIORITY is not a list
```

From the nature of the error messages I suspect that it is an issue with the macro expansion and not with how I am calling. Could you confirm if you can reproduce this behavior? If not, then it could just be an issue with my Lisp environment. Thanks.

**Comment by bohonghuang** [comment]
You are missing an argument `()` when using the macro `run-in-main-event-loop`. Even if you don't specify any options, you cannot ignore it.

Here's an example of how to use it:

https://github.com/bohonghuang/cl-gtk4/blob/ff60e3495cdbba5c09d0bb8aa49f3184cc060c8e/examples/gtk4.lisp#L82-L84

**Comment by hlin91** [comment]
Oh somehow I completely missed that haha. Thanks.
