### ISSUE TITLE
How do I get the list of application windows?

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#7]
https://docs.gtk.org/gtk4/method.Application.get_windows.html

I am trying to find the list of windows associated with the application. Also, how do I programmatically exit from Gtk4 application close all windows and return to REPL?

**Comment by bohonghuang** [comment]
You can obtain and close all windows with:

``` lisp
(let ((windows (mapcar (lambda (ptr)
                         (make-window :pointer ptr))
                       (glib:glist-list (application-windows gio:*application*)))))
  (mapcar #'window-destroy windows))
```

Having closed all your windows, the application quits automatically. Also, you may use `(gtk::destroy-all-windows-and-quit)`, which is internal and can get changed or removed in the future, however.

**Comment by bigos** [comment]
> READ error during LOAD:
> 
>   Symbol "GLIST-LIST" not found in the GLIB package.
> 
>     Line: 661, Column: 94, File-Position: 25012


https://github.com/bigos/Pyrulis/blob/a80b6e18534ed89f59b2e1e596fc8532ac9be9e9/Lisp/cl-gtk4-tictactoe.lisp#L661

**Comment by bigos** [comment]
I use my fork of your project, could that be a problem?

https://github.com/bigos/cl-gtk4

**Comment by bigos** [comment]
```
       (gir:invoke (glib:*ns* "List" 'foreach)
                                                                   (gtk4:application-windows app)
                                                                   #'gtk4:window-close
                                                                   nil)
```

This approach did not work.

I also tried to add wrappers for glib, but they do not expose all the symbols I need.

When I read
/usr/share/gir-1.0/GLib-2.0.gir
and search for g_list_foreach 
I get the impression that the symbols are not introspectable. Do you have any suggestions on how to solve it?

**Comment by bigos** [comment]
Could that be a solution?

```
    (loop for aw = (gtk4:application-active-window app)
                                                             until (null aw)
                                                             do (gtk4:window-close aw))
```

**Comment by bohonghuang** [comment]
> I use my fork of your project, could that be a problem?

Please update [cl-gobject-introspection-wrapper](https://github.com/bohonghuang/cl-gobject-introspection-wrapper), [cl-glib](https://github.com/bohonghuang/cl-glib), and [cl-gtk4](https://github.com/bohonghuang/cl-gtk4) to the latest Git version, where I added some new APIs a few days ago.

**Comment by bohonghuang** [comment]
> I get the impression that the symbols are not introspectable. Do you have any suggestions on how to solve it?

Although they cannot be introspected via GIR, they are accessible through CFFI. The latest `cl-glib` provides `glist-list`, by which you can convert a `GLib.List` to a list in Lisp: https://github.com/bohonghuang/cl-glib/blob/84b128192d6b11cf03f1150e474a23368f07edff/glib/glist.lisp#L179

**Comment by bohonghuang** [comment]
> Could that be a solution?

I may not recommend this method, since it's not guaranteed that `window-close` affects `application-active-window` in one event loop, especially when you attach a custom handler to the `close-request` signal for a window.

**Comment by bigos** [comment]
> > I get the impression that the symbols are not introspectable. Do you have any suggestions on how to solve it?
> 
> Although they cannot be introspected via GIR, they are accessible through CFFI. The latest `cl-glib` provides `glist-list`, by which you can convert a `GLib.List` to a list in Lisp: https://github.com/bohonghuang/cl-glib/blob/84b128192d6b11cf03f1150e474a23368f07edff/glib/glist.lisp#L179

That is the nice response I was looking for. I thought about it as well, but my CFFI skills are very limited and I could not translate CFFI manual to the case I was working on. Your example taught me how to solve those problems where I encounter gir imperfections. Thank you very much!

**Comment by bohonghuang** [comment]
You are welcome.
