### ISSUE TITLE
Compilation errors when installing with (ql:quickload :cl-gtk4)

### ISSUE THREAD

**Issue by bigos** [bohonghuang/cl-gtk4#8]
Quicklisp seems to pull your latest code, but it needs more work. I had to comment out the code in 3 places to have a successful compilation.

Also, with gdk moved to the dependency, I have to modify my example code. 

But it is a nice project and has good potential.

**Comment by bigos** [comment]
The first error. Other errors are similar.

> 
> ; caught ERROR:
> ;   READ error during COMPILE-FILE:
> ;   
> ;     Symbol "GLIST-LIST" not found in the GLIB package.
> ;   
> ;       Line: 51, Column: 26, File-Position: 2043
> ;   
> ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/jacek/quicklisp/local-projects/cl-gtk4/gtk4.lisp" {10028AE9E3}>
>

**Comment by bohonghuang** [comment]
> The first error. Other errors are similar.
> 
> > ; caught ERROR:
> > ;   READ error during COMPILE-FILE:
> > ;
> > ;     Symbol "GLIST-LIST" not found in the GLIB package.
> > ;
> > ;       Line: 51, Column: 26, File-Position: 2043
> > ;
> > ;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/jacek/quicklisp/local-projects/cl-gtk4/gtk4.lisp" {10028AE9E3}>

Have you updated [cl-glib](https://github.com/bohonghuang/cl-glib) and [cl-gobject-introspection-wrapper](https://github.com/bohonghuang/cl-gobject-introspection-wrapper)?

**Comment by bigos** [comment]
How do I do it? Looking at the quicklisp folder, I do not see them. Also, it is getting late here; I will respond tomorrow.
/home/jacek/quicklisp/dists/ultralisp/software

**Comment by bohonghuang** [comment]
> How do I do it? Looking at the quicklisp folder, I do not see them. Also, it is getting late here; I will respond tomorrow. /home/jacek/quicklisp/dists/ultralisp/software

Just clone these 2 repositories into `quicklisp/local-projects`, so that Quicklisp will give priority to loading them.

**Comment by bigos** [comment]
It works. Thank you very much!

**Comment by bigos** [comment]
How do I do g_object_unref after the change?

**Comment by bohonghuang** [comment]
> How do I do g_object_unref after the change?

`(ql:quickload :glib.gobject)` and use `gobj:object-unref`, while it's unnecessary and even unsafe to do this manually in most cases:

``` lisp
(loop :repeat 100000
      :do (mapcar (alexandria:rcurry #'gobj:pointer-object 'window) ; This never leaks memory
                  (glib:glist-list (application-windows app))))
```

**Comment by bigos** [comment]
I mean places like:
https://github.com/bigos/Pyrulis/blob/8bb8c87cfebc8034824a9bc22200f567d7ad213d/Lisp/cl-gtk4-tictactoe.lisp#L741 
https://github.com/bigos/Pyrulis/blob/8bb8c87cfebc8034824a9bc22200f567d7ad213d/Lisp/cl-gtk4-tictactoe.lisp#L668

Some Gtk4 examples require to unref objects.

This is taken from the branch that had to be modified to compile with the new version of cl-gtk4. The old master branch works with older version of cl-gtk4 with my modifications.

It appears the Gtk4 needs it in certain places
https://docs.gtk.org/gobject/method.Object.unref.html
https://stackoverflow.com/questions/69135934/creating-a-simple-menubar-menu-and-menu-item-in-c-using-gtk4

and I do not know how to write working code without calling unref. Do you have any suggestions?

**Comment by bohonghuang** [comment]
Does the code work without `gobj:object-unref`? Some C examples of GTK involve it, because C doesn't manage the memory automatically, forcing the programmer to unref a object when it is no longer needed. But Lisp has GC and can unref the unreachable objects at its own, so there is no point invoking `gobj:object-unref` unless you are interacting with GTK through CFFI.

**Comment by bigos** [comment]
Good question! The memory management questions: https://docs.gtk.org/gtk4/question_index.html , have interesting comments on the subject. Perhaps the following quote will provide further answers for me. I am new to Gtk4, so some of my questions may be a bit wrong.

> The transfer annotations for gobject-introspection that are part of the documentation can provide useful hints for memory handling semantics as well.

**Comment by bigos** [comment]
I have commented out object unref and the code seems to work.

https://github.com/bigos/Pyrulis/commit/dd9e629bc68e8c94d7cc714770461cc3cf3343c9

I did not know about not having to copy everything from C code and use g_object_unref. Thank you very much for your help. The code now works, and after your library changes, it needed only small modifications. You may close the issue.
